md5sum ../../all_graphs.sh all_graphs.sh
md5sum ../../classes.sh classes.sh
md5sum ../../cms.sh cms.sh
md5sum ../../convDate.cpp convDate.cpp
md5sum ../../cp_stats.sh cp_stats.sh
md5sum ../../cpu.sh cpu.sh
md5sum ../../create_all.sh create_all.sh
md5sum ../../gen_script.sh gen_script.sh
md5sum ../../heap.sh heap.sh
md5sum ../../heap_a.sh heap_a.sh
md5sum ../../jvm.sh jvm.sh
md5sum ../../nonheap.sh nonheap.sh
md5sum ../../pareden.sh pareden.sh
md5sum ../../process_servers.sh process_servers.sh
md5sum ../../showTime.cpp showTime.cpp
md5sum ../../threadc.sh threadc.sh
